version: "3.8"

services:
  mongo:
    image: mongo
    restart: unless-stopped 
    ports:
        - "27017:27017"
    environment: 
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=example
    volumes: 
      - ./mongo-init/:/docker-entrypoint-initdb.d/:ro
    networks:      
      - transactions_network

  api:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    command: npm run start:dev
    depends_on:
      - mongo
    ports:
      - 3000:3000
    environment: 
      NODE_ENV: development
      DB_URL: mongodb://root:example@mongo:27017/
      PORT: 3000
    networks:      
      - transactions_network
    
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - .:/app
    command: yarn start
    depends_on:
      - api
    ports:
      - 8000:8000
    environment: 
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:3000
      PORT: 8000
    networks:      
      - transactions_network


    

volumes:
  transactions_db:

networks:
  transactions_network: 
    driver: bridge
